public class CWH_80_Try_Catch_block {
    public static void main(String[] args) {
        int a = 10;
        int b = 2;
        // Without try
        int c = a/b;
        System.out.println("the value of a divided by b is " + c);
        // With try
//        try{
//            int c = a/b;
//            System.out.println("the value of a divided by b is " + c);
//        }
//        catch (Exception e){
//            System.out.println("we failed..");
//            System.out.println(e);
//        }
    }
}